apiVersion: v1
kind: Service
metadata:
  name: velocity-service
  namespace: minecraft
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
    name: mc-port
  selector:
    app: velocity
